<a href="https://colab.research.google.com/github/nurfitrianamldh/python_for_datascience/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

In [ ]:
# pip install numpy

In [ ]:
import numpy as np

## Numpy Create Array

In [ ]:
#@title 0-D Array

var_array = np.array(42)

print(var_array)

42


In [ ]:
#@title 1-D Array

var_array = np.array([1, 2, 3, 4, 5])

print(var_array)

[1 2 3 4 5]


In [ ]:
var_array = np.ones(5)
print(var_array)

[1. 1. 1. 1. 1.]


In [ ]:
var_array = np.zeros(4)
print(var_array)

[0. 0. 0. 0.]


In [ ]:
var_array = np.random.random(6)
print(var_array)

[0.2517622  0.06860088 0.86215751 0.65284615 0.71573341 0.48271725]


In [ ]:
#@title 2-D Array

var_array = np.array([[1, 2, 3], [4, 5, 6]])

print(var_array)

[[1 2 3]
 [4 5 6]]


In [ ]:
#@title 3-D Array

var_array = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(var_array)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
#@title Check dimensi array

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
#@title Create array range
#numpy.arange(start, stop, step)

var_array = np.arange(1, 20, 2)
print(var_array)

[ 1  3  5  7  9 11 13 15 17 19]


In [ ]:
# create with reshape

var_array = np.arange(10).reshape((2, 5))
print(var_array)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
# create numpy text

var_array = np.array(['apple', 'banana', 'cherry'])
print(var_array)

['apple' 'banana' 'cherry']


## Numpy Array Indexing

In [ ]:
#@title Akses indeks

# 1-D
var_array = np.array([85, 55, 40, 90])

# mengakses data pada array
print(var_array[3])

90


In [ ]:
# 2-D
var_array = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(var_array[1, 2])

8


In [ ]:
# 3-D
var_array = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(var_array[1, 1, 2])

12


In [ ]:
#@title Operation indeks

var_array = np.array([1, 2, 3, 4])

print(var_array[2] + var_array[3])

7


In [ ]:
print(var_array[0] + var_array[2])

4


In [ ]:
#@title Slicing array

# 1-D
var_array = np.array([1, 2, 3, 4, 5, 6, 7])

print(var_array[3:])

[4 5 6 7]


In [ ]:
# 2-D
var_array = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(var_array[0, 1:4])

[2 3 4]


In [ ]:
# 3-D
var_array = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(var_array[1, 1, 0:2])

[10 11]


In [ ]:
#@title Iterating Arrays

var_array = np.array([1, 2, 3])

for x in var_array:
  print(x)

1
2
3


In [ ]:
var_array = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in var_array:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


## Numpy Array Join

In [ ]:
#@title Concatenate

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [ ]:
var_array1 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
var_array2 = np.array([[[4, 7, 9], [1, 6, 2]], [[3, 5, 8], [19, 10, 14]]])

arr = np.concatenate((var_array1, var_array2))
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[ 4  7  9]
  [ 1  6  2]]

 [[ 3  5  8]
  [19 10 14]]]


In [ ]:
#@title Stack

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# arr = np.stack((arr1, arr2))
# arr = np.hstack((arr1, arr2))
# arr = np.vstack((arr1, arr2))
arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


## Numpy Splitting

In [ ]:
# 1-D
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 5)

print(newarr)

[array([1, 2]), array([3]), array([4]), array([5]), array([6])]


In [ ]:
# 2-D
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [ ]:
# 3-D
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
newarr = np.array_split(arr, 2)

print(newarr)

[array([[[1, 2, 3],
        [4, 5, 6]]]), array([[[1, 2, 3],
        [4, 5, 6]]])]


## Numpy Matriks

In [ ]:
matriks = [[1,2,3],
           [4,5,6],
           [7,8,9]]

matrik_np = np.array(matriks)
print(matrik_np)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#@title Operasi matrik

matrik_a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]])

matrik_b = np.array([
    [3, 2, 1],
    [6, 5, 4],
    [9, 8, 7]])


hasil = matrik_a + matrik_b
print("Hasil Penjumlahan:")
print(hasil)

Hasil Penjumlahan:
[[ 4  4  4]
 [10 10 10]
 [16 16 16]]


In [ ]:
hasil = matrik_a - matrik_b
print("Hasil Pengurangan:")
print(hasil)

Hasil Pengurangan:
[[-2  0  2]
 [-2  0  2]
 [-2  0  2]]


In [ ]:
# pangkat dengan power()

result_power = np.power(matrik_a, 2)
print("Hasil Perhitungan Pangkat (matrik_a pangkat 2):")
print(result_power)

Hasil Perhitungan Pangkat (matrik_a pangkat 2):
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [ ]:
# trigonometri dengan sin()

result_power = np.sin(matrik_a)
print("Hasil sin matrik_a:")
print(result_power)

Hasil sin matrik_a:
[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825  0.41211849]]


In [ ]:
#@title Transpose matrik

matrik_a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]])

print("Matrik awal: ")
print(matrik_a)


hasil = matrik_a.transpose()
print("\nMatrik kebalikan: ")
print(hasil)

Matrik awal: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrik kebalikan: 
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
#@title Reshape matrik

matrik_a = np.array([1, 2, 3, 4, 5, 6])

print("Matrik awal: ")
print(matrik_a)
print("Ukuran = ", matrik_a.shape)

# mengubah ukran ke 3x2
hasil = matrik_a.reshape(3, 2)

print("\nMengubah ke 3x2: ")
print(hasil)
print("Ukuran = ", hasil.shape)

Matrik awal: 
[1 2 3 4 5 6]
Ukuran =  (6,)

Mengubah ke 3x2: 
[[1 2]
 [3 4]
 [5 6]]
Ukuran =  (3, 2)


In [ ]:
#@title Matrik flatten

matrik_a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]])

print("Matrik awal: ")
print(matrik_a)
print("Ukuran = ", matrik_a.shape)

hasil = matrik_a.flatten()

print("\nMatrik setelah di-flatten: ")
print(hasil)
print("Ukuran = ", hasil.shape)

Matrik awal: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Ukuran =  (3, 3)

Matrik setelah di-flatten: 
[1 2 3 4 5 6 7 8 9]
Ukuran =  (9,)


## Numpy Statistik

In [ ]:
#@title rata-rata (mean)

data = np.array([12, 15, 18, 22, 30, 35, 40, 45, 55, 65])

mean = np.mean(data)
print("Rata-rata (mean):", mean)

Rata-rata (mean): 33.7


In [ ]:
#@title median

median = np.median(data)
print("Median:", median)

Median: 32.5


In [ ]:
#@title standard deviation

std_deviation = np.std(data)
print("Deviasi Standar (standard deviation):", std_deviation)

Deviasi Standar (standard deviation): 16.79315336677421


In [ ]:
#@title variansi (variance)

variance = np.var(data)
print("Variansi (variance):", variance)

Variansi (variance): 282.01


In [ ]:
#@title minimum dan maksimum

minimum = np.min(data)
maximum = np.max(data)
print("Nilai Minimum:", minimum)
print("Nilai Maksimum:", maximum)

Nilai Minimum: 12
Nilai Maksimum: 65


In [ ]:
#@title quartile

# Menghitung kuartil pertama (Q1) dan kuartil ketiga (Q3)
q1 = np.percentile(data, 25)
q3 = np.percentile(data, 75)
print("Kuartil Pertama (Q1):", q1)
print("Kuartil Ketiga (Q3):", q3)


# Menghitung rentang interkuartil (IQR)
iqr = q3 - q1
print("Rentang Interkuartil (IQR):", iqr)

Kuartil Pertama (Q1): 19.0
Kuartil Ketiga (Q3): 43.75
Rentang Interkuartil (IQR): 24.75


## Soal 1

Buat contoh :

* numpy array (1D, 2D, 3D)
* numpy join
* numpy split
* operasi matrik

In [ ]:
#@title Numpy Array (1D, 2D, 3D)

import numpy as np

# 1D Array
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:\n", array_1d)

# 2D Array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D Array:\n", array_2d)

# 3D Array
array_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("\n3D Array:\n", array_3d)

1D Array:
 [1 2 3 4 5]

2D Array:
 [[1 2 3]
 [4 5 6]]

3D Array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
#@title Numpy Join

# Join 1D Arrays
array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])
joined_1d = np.concatenate((array_a, array_b))
print("\nJoined 1D Array:\n", joined_1d)

# Join 2D Arrays along axis 0 (baris)
joined_2d_axis0 = np.concatenate((array_2d, array_2d), axis=0)
print("\nJoined 2D Array (axis=0):\n", joined_2d_axis0)

# Join 2D Arrays along axis 1 (kolom)
joined_2d_axis1 = np.concatenate((array_2d, array_2d), axis=1)
print("\nJoined 2D Array (axis=1):\n", joined_2d_axis1)


Joined 1D Array:
 [1 2 3 4 5 6]

Joined 2D Array (axis=0):
 [[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]

Joined 2D Array (axis=1):
 [[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [ ]:
#@title Numpy Split
# Split 1D Array menjadi 3 bagian
split_1d = np.array_split(array_1d, 3)
print("\nSplit 1D Array:\n", split_1d)

# Split 2D Array menjadi 2 bagian
split_2d = np.array_split(array_2d, 2)
print("\nSplit 2D Array:\n", split_2d)

# Split 3D Array menjadi 2 bagian
split_3d = np.array_split(array_3d, 2)
print("\nSplit 3D Array:\n", split_3d)


Split 1D Array:
 [array([1, 2]), array([3, 4]), array([5])]

Split 2D Array:
 [array([[1, 2, 3]]), array([[4, 5, 6]])]

Split 3D Array:
 [array([[[1, 2, 3],
        [4, 5, 6]]]), array([[[ 7,  8,  9],
        [10, 11, 12]]])]


In [ ]:
#@title Operasi Matrik
# Penjumlahan matriks
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])
matrix_sum = np.add(matrix_a, matrix_b)
print("\nPenjumlahan Matriks:\n", matrix_sum)

# Perkalian matriks (element-wise)
matrix_multiply = np.multiply(matrix_a, matrix_b)
print("\nPerkalian Element-wise Matriks:\n", matrix_multiply)

# Pangkat matriks (power product)
matrix_power = np.power(matrix_a, 2)
print("\nPangkat Product Matriks:\n", matrix_power)

# Transpose matriks
matrix_transpose = np.transpose(matrix_a)
print("\nTranspose Matriks:\n", matrix_transpose)


Penjumlahan Matriks:
 [[ 6  8]
 [10 12]]

Perkalian Element-wise Matriks:
 [[ 5 12]
 [21 32]]

Pangkat Product Matriks:
 [[ 1  4]
 [ 9 16]]

Transpose Matriks:
 [[1 3]
 [2 4]]


## Soal 2

* Buatlah numpy array dengan matrik ukuran 3x4 dan range array 10-30
* Kemudian lakukan flatten
* cari nilai statistik (mean, median, dsb)

In [ ]:
import numpy as np

# Membuat array dengan ukuran 3x4 dan range elemen dari 10 hingga 30
matrix = np.arange(10, 22).reshape(3, 4)
print("Matriks 3x4:\n", matrix)

# Flatten matriks menjadi 1D array
flatten_array = matrix.flatten()
print("\nFlattened Array:\n", flatten_array)

# Mencari nilai statistik
mean_value = np.mean(flatten_array)
median_value = np.median(flatten_array)
min_value = np.min(flatten_array)
max_value = np.max(flatten_array)
std_value = np.std(flatten_array)
var_value = np.var(flatten_array)

print("\nStatistik dari Flattened Array:")
print(f"Mean: {mean_value}")
print(f"Median: {median_value}")
print(f"Minimum: {min_value}")
print(f"Maksimum: {max_value}")
print(f"Standar Deviasi: {std_value}")
print(f"Variansi: {var_value}")

Matriks 3x4:
 [[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]

Flattened Array:
 [10 11 12 13 14 15 16 17 18 19 20 21]

Statistik dari Flattened Array:
Mean: 15.5
Median: 15.5
Minimum: 10
Maksimum: 21
Standar Deviasi: 3.452052529534663
Variansi: 11.916666666666666
